# docker dev farm
# https://github.com/zinan/docker-dev-farm

version: "3"
services:

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "3000:8080"
    networks:
      net:
        ipv4_address: 172.28.1.12
    logging:
      options:
        max-size: 50m

  elasticsearch:
    container_name: elasticsearch
    image: 'bitnami/elasticsearch:7'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    networks:
      net:
        ipv4_address: 172.28.1.11

  elastichq:
    container_name: elastichq
    image: elastichq/elasticsearch-hq
    restart: always
    environment:
      - "HQ_DEFAULT_URL=http://172.28.1.11:9200"
    ports:
      - "5000:5000"
    networks:
      net:
        ipv4_address: 172.28.1.10

  php73:
    build: php7.3
    container_name: php73
    volumes:
      - ${DEFAULT_PROJECTS_FOLDER}:/var/www/html
    networks:
      net:

  php72:
    build: php7.2
    container_name: php72
    volumes:
      - ${DEFAULT_PROJECTS_FOLDER}:/var/www/html
    networks:
      net:

  php71:
    build: php7.1
    container_name: php71
    volumes:
      - ${DEFAULT_PROJECTS_FOLDER}:/var/www/html
    networks:
      net:

  php56:
    build: php5.6
    container_name: php56
    volumes:
      - ${DEFAULT_PROJECTS_FOLDER}:/var/www/html
    networks:
      net:

  apache:
    build: apache
    container_name: apache
    tty: true
    environment:
      - DEFAULT_PROJECTS_FOLDER= ${DEFAULT_PROJECTS_FOLDER}
    volumes:
      - ./apache/sites-enabled:/etc/apache2/sites-enabled
      - ./log/:/var/log/apache2
    links:
      - php73:php73
      - php72:php72
      - php71:php71
      - php56:php56
    ports:
      - ${DEFAULT_APACHE_PORT}:80

  nginx:
    build: nginx
    container_name: nginx
    environment:
      - DEFAULT_PROJECTS_FOLDER= ${DEFAULT_PROJECTS_FOLDER}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log/:/var/log/nginx
      - ./sites:/var/www/html
    links:
      - php73:php73
      - php72:php72
      - php71:php71
      - php56:php56
    ports:
      - ${DEFAULT_NGINX_PORT}:80
    networks:
      net:
        ipv4_address: 172.28.1.1

  mysql:
    build: mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${GLOBAL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${GLOBAL_PASSWORD}
    ports:
      - ${DEFAULT_MYSQL_PORT}:3306
    networks:
      net:
        ipv4_address: 172.28.1.3

  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/var/lib/mongodb
      - MONGO_LOG_DIR=/var/log/mongodb
    volumes:
      - ./data/mongo/mongodb:/var/lib/mongodb
      - ./data/mongo/logs/mongodb:/var/log/mongodb
      - ./data/mongo/data/db:/data/db
    ports:
      - ${DEFAULT_MONGO_PORT}:27017

  redis:
    container_name: redis
    image: redis:alpine
    environment:
      - REDIS_DEFAULT_PASSWORD=${GLOBAL_PASSWORD}
      - MASTER_DEFAULT_PASSWORD=${GLOBAL_PASSWORD}
    ports:
      - ${DEFAULT_REDIS_PORT}:6379

  redis-commander:
    container_name: rediscommander
    build: rediscommander
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${GLOBAL_PASSWORD}
    ports:
      - ${DEFAULT_RCOMMANDER_PORT}:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - ${DEFAULT_MYADMIN_PORT}:80
    links:
      - mysql
    depends_on:
      - mysql
#    environment:
#      PMA_HOST: mysql
    networks:
      net:
        ipv4_address: 172.28.1.4

  nodejs:
    build: nodejs
    container_name: nodejs
    ports:
      - ${DEFAULT_NODEJS_PORT}:3000
    volumes:
      - ${DEFAULT_PROJECTS_FOLDER}:/var/www/html

  postgresql:
    build: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${GLOBAL_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - ${DEFAULT_POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres:/data/postgres

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16


volumes:
  elasticsearch_data:
    driver: local